In [20]:
#0-1 EDAセッティング　基本設定

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

%matplotlib inline
%config Inlinebackend.figure_format='retina'
sns.set(style='whitegrid')
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',100)

In [21]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
#0-2 EDAセッティング　メモリ削減（ダウンキャスト）

total_mem = 0
total_mem_r = 0

def reduce(df):
    global total_mem,total_mem_r

    """ 数値データの型を最適化してメモリを節約する関数 """
    start_mem=df.memory_usage().sum()/1024**2

    for col in df.columns:
      col_type=df[col].dtype
      if col_type != object:
          cmin=df[col].min()
          cmax=df[col].max()

          if str(col_type)[:3]=='int':
            if   cmin > np.iinfo(np.int8).min and cmax < np.iinfo(np.int8).max:
              df[col]=df[col].astype(np.int8)
            elif cmin > np.iinfo(np.int16).min and cmax < np.iinfo(np.int16).max:
              df[col]=df[col].astype(np.int16)
            elif cmin > np.iinfo(np.int32).min and cmax < np.iinfo(np.int32).max:
              df[col]=df[col].astype(np.int32)
            else:
              df[col]=df[col].astype(np.int64)
          else:
            if   cmin > np.finfo(np.float16).min and cmax < np.finfo(np.float16).max:
              df[col]=df[col].astype(np.float16)
            elif cmin > np.finfo(np.float32).min and cmax < np.finfo(np.float32).max:
              df[col]=df[col].astype(np.float32)
            else:
              df[col]=df[col].astype(np.float64)

    end_mem=df.memory_usage().sum()/1024**2
    print(f'メモリ使用量: {start_mem:.2f}MB -> {end_mem:.2f}MB | ',
          f'削減: {(start_mem - end_mem) / start_mem:.2f}MB {100*(start_mem - end_mem) / start_mem:.1f}%')
    total_mem +=start_mem
    total_mem_r +=end_mem
    return df

In [23]:
#0-3 EDAセッティング　csv読込
id_train=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/IEEE-CIS Fraud Detection/元データ/train_identity.csv')
id_train=reduce(id_train)
id_test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/IEEE-CIS Fraud Detection/元データ/test_identity.csv')
id_test=reduce(id_test)

tra_train=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/IEEE-CIS Fraud Detection/元データ/train_transaction.csv')
tra_train=reduce(tra_train)
tra_test=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/IEEE-CIS Fraud Detection/元データ/test_transaction.csv')
tra_test=reduce(tra_test)

sample=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Kaggle/IEEE-CIS Fraud Detection/元データ/sample_submission.csv')
sample=reduce(sample)

total_reduce = total_mem - total_mem_r
total_ratio = 100 * (total_reduce/total_mem)
print('-'*20)
print(f'合計メモリ使用量：{total_mem:.2f}MB -> {total_mem_r:.2f}MB | ',
      f'合計削減: {(total_reduce):.2f}MB {(total_ratio):.2f}%')

#次回以降は以下の形にすると楽
#ALL_PATH = 'リンク先のパス’
#id_train = pd.read_csv(BASE_DIR + 'train_identity.csv')

メモリ使用量: 45.12MB -> 25.86MB |  削減: 0.43MB 42.7%
メモリ使用量: 44.39MB -> 25.44MB |  削減: 0.43MB 42.7%
メモリ使用量: 1775.15MB -> 542.35MB |  削減: 0.69MB 69.4%
メモリ使用量: 1519.24MB -> 472.59MB |  削減: 0.69MB 68.9%
メモリ使用量: 7.73MB -> 2.90MB |  削減: 0.62MB 62.5%
--------------------
合計メモリ使用量：3391.63MB -> 1069.13MB |  合計削減: 2322.49MB 68.48%

In [24]:
#0-4 EDAセッティング　df確認1(ID)
display(pd.concat([id_train.head(4),id_train.tail(2)]))

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11,id_12,id_13,id_14,id_15,id_16,id_17,id_18,id_19,id_20,id_21,id_22,id_23,id_24,id_25,id_26,id_27,id_28,id_29,id_30,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NotFound,NaN,-480.0,New,NotFound,166.0,NaN,542.0,144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NotFound,Android 7.0,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,NaN,100.0,NotFound,49.0,-300.0,New,NotFound,166.0,NaN,621.0,500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NotFound,iOS 11.1.2,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,100.0,NotFound,52.0,NaN,Found,Found,121.0,NaN,410.0,142.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Found,Found,NaN,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,NaN,100.0,NotFound,52.0,NaN,New,NotFound,225.0,NaN,176.0,507.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NotFound,NaN,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
144231,3577531,-5.0,55528.0,0.0,0.0,0.0,-7.0,NaN,NaN,0.0,0.0,100.0,NotFound,27.0,-300.0,Found,Found,166.0,15.0,352.0,368.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Found,Found,Mac OS X 10_9_5,chrome 66.0,24.0,2560x1600,match_status:2,T,F,T,F,desktop,MacOS
144232,3577534,-45.0,339406.0,NaN,NaN,-10.0,-100.0,NaN,NaN,NaN,NaN,100.0,NotFound,27.0,NaN,New,NotFound,225.0,15.0,417.0,595.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NotFound,NaN,chrome 66.0 for android,NaN,NaN,NaN,F,F,T,F,mobile,RNE-L03 Build/HUAWEIRNE-L03

In [25]:
#0-4 EDAセッティング　df確認2(トランザクション)
display(pd.concat([tra_train.head(10),tra_train.tail()]))

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,M1,M2,M3,M4,...,V290,V291,V292,V293,V294,V295,V296,V297,V298,V299,V300,V301,V302,V303,V304,V305,V306,V307,V308,V309,V310,V311,V312,V313,V314,V315,V316,V317,V318,V319,V320,V321,V322,V323,V324,V325,V326,V327,V328,V329,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.500000,W,13926,NaN,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,14.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,NaN,NaN,NaN,0.0,T,T,T,M2,...,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,117.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,117.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.000000,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,M0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.000000,W,4663,490.0,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,315.0,NaN,NaN,NaN,315.0,T,T,T,M0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.000000,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,NaN,2.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,25.0,1.0,112.0,112.0,0.0,94.0,0.0,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,NaN,111.0,NaN,NaN,NaN,M0,...,1.0,1.0,1.0,1.0,38.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,50.000000,1758.000000,925.000000,0.0,354.0000,0.0,135.0,0.0000,0.0000,0.0000,50.0,1404.0,790.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.000000,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2987005,0,86510,49.000000,W,5937,555.0,150.0,visa,226.0,debit,272.0,87.0,36.0,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,T,T,T,M1,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2987006,0,86522,159.000000,W,12308,360.0,150.0,visa,166.0,debit,126.0,87.0,0.0,NaN,yahoo.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,T,T,T,M0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2987007,0,86529,422.500000,W,12695,490.0,150.0,visa,226.0,debit,325.0,87.0,NaN,NaN,mail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,M0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2987008,0,86535,15.000000,H,2803,100.0,150.0,visa,226.0,debit,337.0,87.0,NaN,NaN,anonymous.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2987009,0,86536,117.000000,W,17399,111.0,150.0,mastercard,224.0,debit,204.0,87.0,19.0,NaN,yahoo.com,NaN,2.0,2.0,0.0,0.0,0.0,3.0,0.0,0.0,3.0,0.0,1.0,0.0,12.0,2.0,61.0,61.0,30.0,318.0,30.0,NaN,NaN,NaN,NaN,40.0,302.0,NaN,NaN,NaN,318.0,T,T,T,M0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,495.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590535,3577535,0,15811047,49.000000,W,6550,NaN,150.0,visa,226.0,debit,272.0,87.0,48.0,NaN,NaN,NaN,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,1.0,0.0,3.0,2.0,29.0,29.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN,56.0,56.0,NaN,NaN,NaN,56.0,T,T,T,M0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,47.950001,0.000000,0.0,47.9375,0.0,0.0,47.9375,47.9375,47.9375,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590536,3577536,0,15811049,39.500000,W,10444,225.0,150.0,mastercard,224.0,debit,204.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,T,F,F,M0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590537,3577537,0,15811079,30.953125,W,12037,595.0,150.0,mastercard,224.0,debit,231.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,T,F,F,NaN,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590538,3577538,0,15811088,117.000000,W,7826,481.0,150.0,mastercard,224.0,debit,387.0,87.0,3.0,NaN,aol.com,NaN,1.0,1.0,0.0,0.0,0.0,3.0,0.0,0.0,2.0,0.0,1.0,1.0,5.0,1.0,22.0,22.0,0.0,22.0,0.0,NaN,NaN,NaN,NaN,22.0,22.0,NaN,NaN,NaN,22.0,T,T,T,M0,...,1.0,2.0,1.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,117.000000,2903.500000,117.000000,117.0,669.5000,0.0,117.0,317.5000,669.5000,317.5000,0.0,2234.0,0.0,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590539,3577539,0,15811131,280.000000,W,15066,170.0,150.0,mastercard,102.0,credit,299.0,87.0,NaN,NaN,gmail.com,NaN,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,1.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,1.0,T,F,F,NaN,...,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,279.950012,279.950012,279.950012,0.0,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.0,0.0,0.0,279.950012,279.950012,279.950012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
#0-4 EDAセッティング　df確認3(カラム説明　Kaggleより引用)

'''
【アイデンティティテーブル】
このテーブル内の変数は、取引に関連付けられた識別情報（ネットワーク接続情報
（IP、ISP、プロキシなど）とデジタル署名（UA/ブラウザ/OS/バージョンなど））
です。
これらは、Vestaの不正防止システムとデジタルセキュリティパートナーによって収
集されます。
（フィールド名はマスクされており、プライバシー保護と契約締結のため、ペアワイ
ズ辞書は提供されません。）

カテゴリ別特徴: DeviceType DeviceInfo id_12 - id_38

【取引表】
TransactionDT: 指定された参照日時からのタイムデルタ（実際のタイムスタンプで
　　　　　　　 はありません）
TransactionAMT: 取引支払金額（米ドル）
ProductCD: 製品コード、各トランザクションの製品
card1 - card6: カードの種類、カードのカテゴリ、発行銀行、国などの支払いカー
               ド情報。
addr: 住所
dist: 距離
P_ および (R__) emaildomain: 購入者と受信者のメールドメイン
C1-C14: 支払いカードに関連付けられているアドレスがいくつ見つかったかなどのカ
　　　　ウント。実際の意味はマスクされています。
D1-D15: 前回の取引間の日数などの時間差分。
M1-M9: カード名や住所などが一致します。
Vxxx: Vesta は、ランキング、カウント、その他のエンティティ関係を含む豊富な機
　　　能を設計しました。
カテゴリカル特徴: ProductCD card1 - card6 addr1, addr2 P_emaildomain
                  R_emaildomain M1 - M9

'''

'\n【アイデンティティテーブル】\nこのテーブル内の変数は、取引に関連付けられた識別情報（ネットワーク接続情報\n（IP、ISP、プロキシなど）とデジタル署名（UA/ブラウザ/OS/バージョンなど））\nです。\nこれらは、Vestaの不正防止システムとデジタルセキュリティパートナーによって収\n集されます。\n（フィールド名はマスクされており、プライバシー保護と契約締結のため、ペアワイ\nズ辞書は提供されません。）\n\nカテゴリ別特徴: DeviceType DeviceInfo id_12 - id_38\n\n【取引表】\nTransactionDT: 指定された参照日時からのタイムデルタ（実際のタイムスタンプで\n\u3000\u3000\u3000\u3000\u3000\u3000\u3000 はありません）\nTransactionAMT: 取引支払金額（米ドル）\nProductCD: 製品コード、各トランザクションの製品\ncard1 - card6: カードの種類、カードのカテゴリ、発行銀行、国などの支払いカー\n               ド情報。\naddr: 住所\ndist: 距離\nP_ および (R__) emaildomain: 購入者と受信者のメールドメイン\nC1-C14: 支払いカードに関連付けられているアドレスがいくつ見つかったかなどのカ\n\u3000\u3000\u3000\u3000ウント。実際の意味はマスクされています。\nD1-D15: 前回の取引間の日数などの時間差分。\nM1-M9: カード名や住所などが一致します。\nVxxx: Vesta は、ランキング、カウント、その他のエンティティ関係を含む豊富な機\n\u3000\u3000\u3000能を設計しました。\nカテゴリカル特徴: ProductCD card1 - card6 addr1, addr2 P_emaildomain\n                  R_emaildomain M1 - M9\n\n'

In [27]:
#0-4 EDAセッティング　df確認4(提出データ)
sample

        TransactionID  isFraud
0             3663549      0.5
1             3663550      0.5
2             3663551      0.5
3             3663552      0.5
4             3663553      0.5
...               ...      ...
506686        4170235      0.5
506687        4170236      0.5
506688        4170237      0.5
506689        4170238      0.5
506690        4170239      0.5

[506691 rows x 2 columns]

In [28]:
#0-5 EDAセッティング　欠損値確認(train)

id_and_tra=[('Identity',id_train),('Transaction',tra_train)]

def missing(id_and_tra):

  for name,df in id_and_tra:
    null_counts=df.isnull().sum()
    null_columns=null_counts[null_counts > 0]
    mis_ratio=len(null_columns)/len(df.columns)*100

    if null_counts.empty:
        print('欠損値なし')
    else:
        print(f'【{name}: 欠損あり(全{len(df.columns)}カラム中) {len(null_columns)}件】 ({mis_ratio:.2f}%)')
        tmp_df=null_columns.to_frame(name='ncounts')
        tmp_df['ratio']=(tmp_df['ncounts'] / len(df)) * 100
        df_ratio_desc=tmp_df.sort_values('ratio',ascending=False)

        for ncol,row in df_ratio_desc.iterrows():
            count = row['ncounts']
            ratio = row['ratio']
            print(f'カラム名: {ncol:<15} | 欠損数: {int(count):>8} / 全レコード数: {len(df)} | 割合: {ratio:>6.2f}%')
        print('*'*100)

  return df_ratio_desc

mis_train=missing(id_and_tra)

【Identity: 欠損あり(全41カラム中) 38件】 (92.68%)
カラム名: id_24           | 欠損数:   139486 / 全レコード数: 144233 | 割合:  96.71%
カラム名: id_25           | 欠損数:   139101 / 全レコード数: 144233 | 割合:  96.44%
カラム名: id_07           | 欠損数:   139078 / 全レコード数: 144233 | 割合:  96.43%
カラム名: id_08           | 欠損数:   139078 / 全レコード数: 144233 | 割合:  96.43%
カラム名: id_21           | 欠損数:   139074 / 全レコード数: 144233 | 割合:  96.42%
カラム名: id_26           | 欠損数:   139070 / 全レコード数: 144233 | 割合:  96.42%
カラム名: id_22           | 欠損数:   139064 / 全レコード数: 144233 | 割合:  96.42%
カラム名: id_27           | 欠損数:   139064 / 全レコード数: 144233 | 割合:  96.42%
カラム名: id_23           | 欠損数:   139064 / 全レコード数: 144233 | 割合:  96.42%
カラム名: id_18           | 欠損数:    99120 / 全レコード数: 144233 | 割合:  68.72%
カラム名: id_03           | 欠損数:    77909 / 全レコード数: 144233 | 割合:  54.02%
カラム名: id_04           | 欠損数:    77909 / 全レコード数: 144233 | 割合:  54.02%
カラム名: id_33           | 欠損数:    70944 / 全レコード数: 144233 | 割合:  49.19%
カラム名: id_10           | 欠損数:    69307 / 全レコード数: 144233 | 割合:  48.05%
カラム名: id_09           | 欠損数:    69307 / 全レコード数: 144233 | 割合:  48.05%
カラム名: id_30           | 欠損数:    66668 / 全レコード数: 144233 | 割合:  46.22%
カラム名: id_32           | 欠損数:    66647 / 全レコード数: 144233 | 割合:  46.21%
カラム名: id_34           | 欠損数:    66428 / 全レコード数: 144233 | 割合:  46.06%
カラム名: id_14           | 欠損数:    64189 / 全レコード数: 144233 | 割合:  44.50%
カラム名: DeviceInfo      | 欠損数:    25567 / 全レコード数: 144233 | 割合:  17.73%
カラム名: id_13           | 欠損数:    16913 / 全レコード数: 144233 | 割合:  11.73%
カラム名: id_16           | 欠損数:    14893 / 全レコード数: 144233 | 割合:  10.33%
カラム名: id_05           | 欠損数:     7368 / 全レコード数: 144233 | 割合:   5.11%
カラム名: id_06           | 欠損数:     7368 / 全レコード数: 144233 | 割合:   5.11%
カラム名: id_20           | 欠損数:     4972 / 全レコード数: 144233 | 割合:   3.45%
カラム名: id_19           | 欠損数:     4915 / 全レコード数: 144233 | 割合:   3.41%
カラム名: id_17           | 欠損数:     4864 / 全レコード数: 144233 | 割合:   3.37%
カラム名: id_31           | 欠損数:     3951 / 全レコード数: 144233 | 割合:   2.74%
カラム名: DeviceType      | 欠損数:     3423 / 全レコード数: 144233 | 割合:   2.37%
カラム名: id_02           | 欠損数:     3361 / 全レコード数: 144233 | 割合:   2.33%
カラム名: id_29           | 欠損数:     3255 / 全レコード数: 144233 | 割合:   2.26%
カラム名: id_11           | 欠損数:     3255 / 全レコード数: 144233 | 割合:   2.26%
カラム名: id_28           | 欠損数:     3255 / 全レコード数: 144233 | 割合:   2.26%
カラム名: id_15           | 欠損数:     3248 / 全レコード数: 144233 | 割合:   2.25%
カラム名: id_36           | 欠損数:     3248 / 全レコード数: 144233 | 割合:   2.25%
カラム名: id_35           | 欠損数:     3248 / 全レコード数: 144233 | 割合:   2.25%
カラム名: id_38           | 欠損数:     3248 / 全レコード数: 144233 | 割合:   2.25%
カラム名: id_37           | 欠損数:     3248 / 全レコード数: 144233 | 割合:   2.25%
****************************************************************************************************
【Transaction: 欠損あり(全394カラム中) 374件】 (94.92%)
カラム名: dist2           | 欠損数:   552913 / 全レコード数: 590540 | 割合:  93.63%
カラム名: D7              | 欠損数:   551623 / 全レコード数: 590540 | 割合:  93.41%
カラム名: D13             | 欠損数:   528588 / 全レコード数: 590540 | 割合:  89.51%
カラム名: D14             | 欠損数:   528353 / 全レコード数: 590540 | 割合:  89.47%
カラム名: D12             | 欠損数:   525823 / 全レコード数: 590540 | 割合:  89.04%
カラム名: D6              | 欠損数:   517353 / 全レコード数: 590540 | 割合:  87.61%
カラム名: D8              | 欠損数:   515614 / 全レコード数: 590540 | 割合:  87.31%
カラム名: D9              | 欠損数:   515614 / 全レコード数: 590540 | 割合:  87.31%
カラム名: V154            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V153            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V162            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V161            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V163            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V155            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V156            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V138            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V142            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V149            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V148            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V147            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V146            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V139            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V140            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V157            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V158            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V141            | 欠損数:   508595 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V159            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V166            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V150            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V145            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V144            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V165            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V164            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V152            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V160            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V151            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V143            | 欠損数:   508589 / 全レコード数: 590540 | 割合:  86.12%
カラム名: V339            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V334            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V336            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V335            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V333            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V332            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V331            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V330            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V326            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V327            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V328            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V329            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V322            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V323            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V324            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V325            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V338            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V337            | 欠損数:   508189 / 全レコード数: 590540 | 割合:  86.05%
カラム名: V262            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V263            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V266            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V267            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V264            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V265            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V276            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V275            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V274            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V273            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V278            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V277            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V268            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V269            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V240            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V241            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V242            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V243            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V244            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V246            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V247            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V248            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V249            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V252            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V253            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V254            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V257            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V258            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V260            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V261            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V237            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V236            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V235            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V233            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V232            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V231            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V230            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V229            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V228            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V226            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V225            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V224            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V223            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V219            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V218            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: V217            | 欠損数:   460110 / 全レコード数: 590540 | 割合:  77.91%
カラム名: R_emaildomain   | 欠損数:   453249 / 全レコード数: 590540 | 割合:  76.75%
カラム名: V168            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V182            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V177            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V176            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V178            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V172            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V207            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V173            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V205            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V206            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V203            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V196            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V199            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V202            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V212            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V204            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V215            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V216            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V213            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V211            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V214            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V186            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V190            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V183            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V181            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V187            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V192            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V191            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V193            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V179            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V167            | 欠損数:   450909 / 全レコード数: 590540 | 割合:  76.36%
カラム名: V209            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V180            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V210            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V189            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V194            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V185            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V184            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V170            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V169            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V175            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V197            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V201            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V208            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V198            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V188            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V171            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V174            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V195            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V200            | 欠損数:   450721 / 全レコード数: 590540 | 割合:  76.32%
カラム名: V255            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V270            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V272            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V256            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V221            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V271            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V259            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V227            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V222            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V245            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V251            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V250            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V239            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V220            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V234            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: V238            | 欠損数:   449124 / 全レコード数: 590540 | 割合:  76.05%
カラム名: dist1           | 欠損数:   352271 / 全レコード数: 590540 | 割合:  59.65%
カラム名: M5              | 欠損数:   350482 / 全レコード数: 590540 | 割合:  59.35%
カラム名: M7              | 欠損数:   346265 / 全レコード数: 590540 | 割合:  58.64%
カラム名: M8              | 欠損数:   346252 / 全レコード数: 590540 | 割合:  58.63%
カラム名: M9              | 欠損数:   346252 / 全レコード数: 590540 | 割合:  58.63%
カラム名: D5              | 欠損数:   309841 / 全レコード数: 590540 | 割合:  52.47%
カラム名: M4              | 欠損数:   281444 / 全レコード数: 590540 | 割合:  47.66%
カラム名: D2              | 欠損数:   280797 / 全レコード数: 590540 | 割合:  47.55%
カラム名: V2              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V1              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V4              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V3              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V11             | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V10             | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V9              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: D11             | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V5              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V6              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V8              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: V7              | 欠損数:   279287 / 全レコード数: 590540 | 割合:  47.29%
カラム名: M3              | 欠損数:   271100 / 全レコード数: 590540 | 割合:  45.91%
カラム名: M2              | 欠損数:   271100 / 全レコード数: 590540 | 割合:  45.91%
カラム名: M1              | 欠損数:   271100 / 全レコード数: 590540 | 割合:  45.91%
カラム名: D3              | 欠損数:   262878 / 全レコード数: 590540 | 割合:  44.51%
カラム名: M6              | 欠損数:   169360 / 全レコード数: 590540 | 割合:  28.68%
カラム名: V37             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V51             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V52             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V49             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V50             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V41             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V42             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V36             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V35             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V45             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V46             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V47             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V48             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V39             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V40             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V38             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V44             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: V43             | 欠損数:   168969 / 全レコード数: 590540 | 割合:  28.61%
カラム名: D4              | 欠損数:   168922 / 全レコード数: 590540 | 割合:  28.60%
カラム名: P_emaildomain   | 欠損数:    94456 / 全レコード数: 590540 | 割合:  15.99%
カラム名: V89             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V84             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V85             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V86             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V87             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V80             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V79             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V94             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V92             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V75             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V76             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V90             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V91             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V88             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V83             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V82             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V93             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V81             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V78             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: V77             | 欠損数:    89164 / 全レコード数: 590540 | 割合:  15.10%
カラム名: D15             | 欠損数:    89113 / 全レコード数: 590540 | 割合:  15.09%
カラム名: V61             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V56             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V57             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V58             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V59             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V62             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V53             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V54             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V55             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V65             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V67             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V66             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V73             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V72             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%
カラム名: V68             | 欠損数:    77096 / 全レコード数: 590540 | 割合:  13.06%

９割超のカラムが欠損値あり
マージ後のデータで再度要検討

In [29]:
#0-5 EDAセッティング　無欠損値確認(train)

def not_missing(id_and_tra):

  for name, df in id_and_tra:
      null_counts = df.isnull().sum()
      clean_columns = null_counts[null_counts == 0].index.tolist()

      print(f"--- 【{name}】 無欠損カラム一覧 (計 {len(clean_columns)}件) ---")
      if len(clean_columns) > 0:
          for i in range(0, len(clean_columns), 5):
              print(", ".join(clean_columns[i:i+5]))
      else:
        print("無欠損なし")
      print("\n" + "="*50 + "\n")

  return id_and_tra
not_mis_train=not_missing(id_and_tra)

--- 【Identity】 無欠損カラム一覧 (計 3件) ---
TransactionID, id_01, id_12

==================================================

--- 【Transaction】 無欠損カラム一覧 (計 20件) ---
TransactionID, isFraud, TransactionDT, TransactionAmt, ProductCD
card1, C1, C2, C3, C4
C5, C6, C7, C8, C9
C10, C11, C12, C13, C14

==================================================

isFraud欠損なしを確認、また結合キー(TransactionID)も欠損なし

In [30]:
#0-5 EDAセッティング　欠損値確認(test)

test_mis_nmis=[('Identity',id_test),('Transaction',tra_test)]
not_mis_test=not_missing(test_mis_nmis)
mis_test=missing(test_mis_nmis)

--- 【Identity】 無欠損カラム一覧 (計 3件) ---
TransactionID, id-01, id-12

==================================================

--- 【Transaction】 無欠損カラム一覧 (計 48件) ---
TransactionID, TransactionDT, TransactionAmt, ProductCD, card1
V95, V96, V97, V98, V99
V100, V101, V102, V103, V104
V105, V106, V107, V108, V109
V110, V111, V112, V113, V114
V115, V116, V117, V118, V119
V120, V121, V122, V123, V124
V125, V126, V127, V128, V129
V130, V131, V132, V133, V134
V135, V136, V137

==================================================

【Identity: 欠損あり(全41カラム中) 38件】 (92.68%)
カラム名: id-24           | 欠損数:   137167 / 全レコード数: 141907 | 割合:  96.66%
カラム名: id-25           | 欠損数:   136868 / 全レコード数: 141907 | 割合:  96.45%
カラム名: id-26           | 欠損数:   136860 / 全レコード数: 141907 | 割合:  96.44%
カラム名: id-08           | 欠損数:   136848 / 全レコード数: 141907 | 割合:  96.43%
カラム名: id-07           | 欠損数:   136848 / 全レコード数: 141907 | 割合:  96.43%
カラム名: id-21           | 欠損数:   136848 / 全レコード数: 141907 | 割合:  96.43%
カラム名: id-22           | 欠損数:   136845 / 全レコード数: 141907 | 割合:  96.43%
カラム名: id-27           | 欠損数:   136845 / 全レコード数: 141907 | 割合:  96.43%
カラム名: id-23           | 欠損数:   136845 / 全レコード数: 141907 | 割合:  96.43%
カラム名: id-18           | 欠損数:    91032 / 全レコード数: 141907 | 割合:  64.15%
カラム名: id-03           | 欠損数:    75426 / 全レコード数: 141907 | 割合:  53.15%
カラム名: id-04           | 欠損数:    75426 / 全レコード数: 141907 | 割合:  53.15%
カラム名: id-30           | 欠損数:    71248 / 全レコード数: 141907 | 割合:  50.21%
カラム名: id-33           | 欠損数:    71236 / 全レコード数: 141907 | 割合:  50.20%
カラム名: id-32           | 欠損数:    71236 / 全レコード数: 141907 | 割合:  50.20%
カラム名: id-14           | 欠損数:    70550 / 全レコード数: 141907 | 割合:  49.72%
カラム名: id-34           | 欠損数:    69732 / 全レコード数: 141907 | 割合:  49.14%
カラム名: id-09           | 欠損数:    67569 / 全レコード数: 141907 | 割合:  47.61%
カラム名: id-10           | 欠損数:    67569 / 全レコード数: 141907 | 割合:  47.61%
カラム名: DeviceInfo      | 欠損数:    26850 / 全レコード数: 141907 | 割合:  18.92%
カラム名: id-16           | 欠損数:    16160 / 全レコード数: 141907 | 割合:  11.39%
カラム名: id-13           | 欠損数:    11621 / 全レコード数: 141907 | 割合:   8.19%
カラム名: id-05           | 欠損数:     7157 / 全レコード数: 141907 | 割合:   5.04%
カラム名: id-06           | 欠損数:     7157 / 全レコード数: 141907 | 割合:   5.04%
カラム名: id-20           | 欠損数:     6274 / 全レコード数: 141907 | 割合:   4.42%
カラム名: id-19           | 欠損数:     6001 / 全レコード数: 141907 | 割合:   4.23%
カラム名: id-17           | 欠損数:     5941 / 全レコード数: 141907 | 割合:   4.19%
カラム名: id-31           | 欠損数:     5282 / 全レコード数: 141907 | 割合:   3.72%
カラム名: id-29           | 欠損数:     5129 / 全レコード数: 141907 | 割合:   3.61%
カラム名: id-11           | 欠損数:     5129 / 全レコード数: 141907 | 割合:   3.61%
カラム名: id-28           | 欠損数:     5129 / 全レコード数: 141907 | 割合:   3.61%
カラム名: DeviceType      | 欠損数:     4976 / 全レコード数: 141907 | 割合:   3.51%
カラム名: id-02           | 欠損数:     4931 / 全レコード数: 141907 | 割合:   3.47%
カラム名: id-15           | 欠損数:     4930 / 全レコード数: 141907 | 割合:   3.47%
カラム名: id-36           | 欠損数:     4930 / 全レコード数: 141907 | 割合:   3.47%
カラム名: id-35           | 欠損数:     4930 / 全レコード数: 141907 | 割合:   3.47%
カラム名: id-38           | 欠損数:     4930 / 全レコード数: 141907 | 割合:   3.47%
カラム名: id-37           | 欠損数:     4930 / 全レコード数: 141907 | 割合:   3.47%
****************************************************************************************************
【Transaction: 欠損あり(全393カラム中) 345件】 (87.79%)
カラム名: dist2           | 欠損数:   470255 / 全レコード数: 506691 | 割合:  92.81%
カラム名: D7              | 欠損数:   446558 / 全レコード数: 506691 | 割合:  88.13%
カラム名: D12             | 欠損数:   437437 / 全レコード数: 506691 | 割合:  86.33%
カラム名: D8              | 欠損数:   432353 / 全レコード数: 506691 | 割合:  85.33%
カラム名: D9              | 欠損数:   432353 / 全レコード数: 506691 | 割合:  85.33%
カラム名: V154            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V162            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V146            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V149            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V138            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V142            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V161            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V157            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V155            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V163            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V158            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V153            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V140            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V141            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V147            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V139            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V148            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V156            | 欠損数:   430906 / 全レコード数: 506691 | 割合:  85.04%
カラム名: V164            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V150            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V166            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V152            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V151            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V165            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V143            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V144            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V145            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V159            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V160            | 欠損数:   430636 / 全レコード数: 506691 | 割合:  84.99%
カラム名: V330            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V331            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V332            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V329            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V333            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V335            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V336            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V337            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V338            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V339            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V326            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V322            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V323            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V324            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V327            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V325            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V328            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: V334            | 欠損数:   430260 / 全レコード数: 506691 | 割合:  84.92%
カラム名: D14             | 欠損数:   391497 / 全レコード数: 506691 | 割合:  77.27%
カラム名: D13             | 欠損数:   383307 / 全レコード数: 506691 | 割合:  75.65%
カラム名: D6              | 欠損数:   381908 / 全レコード数: 506691 | 割合:  75.37%
カラム名: V278            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V262            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V263            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V264            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V265            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V266            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V267            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V268            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V269            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V274            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V275            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V273            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V276            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V277            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V257            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V261            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V260            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V241            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V240            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V237            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V236            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V235            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V258            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V254            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V253            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V252            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V249            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V248            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V247            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V246            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V244            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V243            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V242            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V219            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V223            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V224            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V225            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V226            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V228            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V229            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V230            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V231            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V232            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V233            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V218            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: V217            | 欠損数:   379963 / 全レコード数: 506691 | 割合:  74.99%
カラム名: R_emaildomain   | 欠損数:   370821 / 全レコード数: 506691 | 割合:  73.18%
カラム名: V175            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V180            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V174            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V171            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V169            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V198            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V195            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V188            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V189            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V194            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V201            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V200            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V197            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V208            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V210            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V209            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V184            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V185            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V170            | 欠損数:   370316 / 全レコード数: 506691 | 割合:  73.09%
カラム名: V187            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V192            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V190            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V193            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V202            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V199            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V196            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V211            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V212            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V213            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V207            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V206            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V205            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V204            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V203            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V215            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V216            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V214            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V191            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V167            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V168            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V182            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V178            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V179            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V181            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V173            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V172            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V176            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V177            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V183            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V186            | 欠損数:   369957 / 全レコード数: 506691 | 割合:  73.01%
カラム名: V220            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V256            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V271            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V270            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V259            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V272            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V255            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V250            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V245            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V239            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V251            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V234            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V227            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V238            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V221            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: V222            | 欠損数:   369375 / 全レコード数: 506691 | 割合:  72.90%
カラム名: M5              | 欠損数:   309632 / 全レコード数: 506691 | 割合:  61.11%
カラム名: dist1           | 欠損数:   291217 / 全レコード数: 506691 | 割合:  57.47%
カラム名: M4              | 欠損数:   237745 / 全レコード数: 506691 | 割合:  46.92%
カラム名: M7              | 欠損数:   235018 / 全レコード数: 506691 | 割合:  46.38%
カラム名: M9              | 欠損数:   235004 / 全レコード数: 506691 | 割合:  46.38%
カラム名: M8              | 欠損数:   235004 / 全レコード数: 506691 | 割合:  46.38%
カラム名: D2              | 欠損数:   234769 / 全レコード数: 506691 | 割合:  46.33%
カラム名: D5              | 欠損数:   224375 / 全レコード数: 506691 | 割合:  44.28%
カラム名: D3              | 欠損数:   203142 / 全レコード数: 506691 | 割合:  40.09%
カラム名: M3              | 欠損数:   176639 / 全レコード数: 506691 | 割合:  34.86%
カラム名: M2              | 欠損数:   176639 / 全レコード数: 506691 | 割合:  34.86%
カラム名: M1              | 欠損数:   176639 / 全レコード数: 506691 | 割合:  34.86%
カラム名: V11             | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V5              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V10             | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V6              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V7              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V3              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V2              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: D11             | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V4              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V9              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V1              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: V8              | 欠損数:   176518 / 全レコード数: 506691 | 割合:  34.84%
カラム名: M6              | 欠損数:   158939 / 全レコード数: 506691 | 割合:  31.37%
カラム名: V37             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V38             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V39             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V40             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V42             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V41             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V45             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V46             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V43             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V47             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V49             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V50             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V51             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V44             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V48             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V52             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V36             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: V35             | 欠損数:    76854 / 全レコード数: 506691 | 割合:  15.17%
カラム名: D4              | 欠損数:    76851 / 全レコード数: 506691 | 割合:  15.17%
カラム名: P_emaildomain   | 欠損数:    69192 / 全レコード数: 506691 | 割合:  13.66%
カラム名: addr2           | 欠損数:    65609 / 全レコード数: 506691 | 割合:  12.95%
カラム名: addr1           | 欠損数:    65609 / 全レコード数: 506691 | 割合:  12.95%
カラム名: V70             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V55             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V71             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V61             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V62             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V63             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V67             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V68             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V64             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V56             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V60             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V59             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V58             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V57             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V53             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V54             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V65             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V66             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V69             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V72             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V74             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V73             | 欠損数:    12899 / 全レコード数: 506691 | 割合:   2.55%
カラム名: V12             | 欠損数:    12589 / 全レコード数: 506691 | 割合:   2.48%
カラム名: V33             | 欠損数:    12589 / 全レコード数: 506691 | 割合:   2.48%
カラム名: V34             | 欠損数:    12589 / 全レコード数: 506691 | 割合:   2.48%
カラム名: V32             | 欠損数:    12589 / 全レコード数: 506691 | 割合:   2.48%

In [31]:
#0-6 EDAセッティング　結合キー重複確認

for name,df in id_and_tra:
  df=df.groupby('TransactionID').size()
  print(f'【{name}】{df.sum()}件')
  df_max=df.max()

  if df_max > 1:
    print(f'【{name}】重複あり')
    print(f'最大重複回数:{df_max}')
  else:
    print(f'【{name}】重複なし')

【Identity】144233件
【Identity】重複なし
【Transaction】590540件
【Transaction】重複なし

In [32]:
#0-7 EDAセッティング　結合(train & test)

train = pd.merge(tra_train,id_train,on='TransactionID',how='left')
test = pd.merge(tra_test,id_test,on='TransactionID',how='left')

print(f'レコード数(train)：{train.shape[0]}')
print(f'カラム数(train)：{train.shape[1]}')
print(f'レコード数(test)：{test.shape[0]}')
print(f'カラム数(test)：{test.shape[1]}')

train.head()

レコード数(train)：590540
カラム数(train)：434
レコード数(test)：506691
カラム数(test)：433

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,addr2,dist1,dist2,P_emaildomain,R_emaildomain,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D11,D12,D13,D14,D15,M1,M2,M3,M4,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,id_10,id_11,id_12,id_13,id_14,id_15,id_16,id_17,id_18,id_19,id_20,id_21,id_22,id_23,id_24,id_25,id_26,id_27,id_28,id_29,id_30,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0,87.0,19.0,NaN,NaN,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,1.0,1.0,14.0,NaN,13.0,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,NaN,NaN,NaN,0.0,T,T,T,M2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,M0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0,87.0,287.0,NaN,outlook.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,315.0,NaN,NaN,NaN,315.0,T,T,T,M0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0,87.0,NaN,NaN,yahoo.com,NaN,2.0,5.0,0.0,0.0,0.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,25.0,1.0,112.0,112.0,0.0,94.0,0.0,NaN,NaN,NaN,NaN,84.0,NaN,NaN,NaN,NaN,111.0,NaN,NaN,NaN,M0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0,87.0,NaN,NaN,gmail.com,NaN,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NotFound,NaN,-480.0,New,NotFound,166.0,NaN,542.0,144.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New,NotFound,Android 7.0,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M

カラムの差:isFraud

In [33]:
#0-7 EDAセッティング　再ダウンキャスト及び出力（パーケ形式）
train=reduce(train)
test=reduce(test)

train.to_parquet('train_merged.parquet')
test.to_parquet('test_merged.parquet')

メモリ使用量: 645.97MB -> 645.97MB |  削減: 0.00MB 0.0%
メモリ使用量: 561.50MB -> 561.50MB |  削減: 0.00MB 0.0%

マージ処理により、サイズがアップキャストされる可能性があるため再ダウンキャストを実施。  
今回は初期の処理により削減なし。

In [34]:
'''
後続処理
①下処理前EDA
②欠損処理の検討
③特徴量変換(ビン分け、外れ値処理、ラベル化の検討)
④下処理後EDA
'''

'\n後続処理\n①下処理前EDA\n②欠損処理の検討\n③特徴量変換(ビン分け、外れ値処理、ラベル化の検討)\n④下処理後EDA\n'